### ISSUE TITLE
PJ, why is this not working? Sorry I see my domain was wrong

### ISSUE THREAD

**Issue by StormArt** [pjmuller/zendesk-helpcenter-export#10]
storms-Mac-mini:~ Storm$ cd desktop
storms-Mac-mini:desktop Storm$ cd zendeskexport
storms-Mac-mini:zendeskexport Storm$ ruby zendesk-helpcenter-export.rb -e username@intelliacc.com -p password -d http://support.intelliacc.com/hc/en-us
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: nodename nor servname provided, or not known (SocketError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in`open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in`timeout'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in`do_start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in`request'
    from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.7/lib/httparty/request.rb:117:in `perform'
    from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.7/lib/httparty.rb:545:in`perform_request'
    from /Library/Ruby/Gems/2.0.0/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
    from zendesk-helpcenter-export.rb:255:in`api'
    from zendesk-helpcenter-export.rb:279:in `categories'
    from zendesk-helpcenter-export.rb:76:in`to_html!'
    from zendesk-helpcenter-export.rb:329:in `<main>'
storms-Mac-mini:zendeskexport Storm$

**Comment by pjmuller** [comment]
@StormArt , 1) happy that you solved it yourself 2) in your issue report you posted your password. Please quickly change it as otherwise others will access your account.
