### ISSUE TITLE
FileUtils not found on *nix systems

### ISSUE THREAD

**Issue by 4levels** [pjmuller/zendesk-helpcenter-export#11]
The requirement `FileUtils` generates an error on Debian7 (and probably on other Linux distro's).
Using `fileutils` (all lowercase) fixes this. According to StackOverffow the cased version only works in Mac OsX.

**Comment by pjmuller** [comment]
Hi @4levels , thanks for pointing it out. I fixed it in https://github.com/pjmuller/zendesk-helpcenter-export/commit/f34d425abbc61ff895c8b6c62edb6eb48ce78fee
