### ISSUE TITLE
Cannot load Required gems

### ISSUE THREAD

**Issue by ComprensivoDK** [pjmuller/zendesk-helpcenter-export#2]
I get this error when trying to run the script. Seems that the required gems can't be found - Perhaps you can describe what gems are required and how to install them? 

C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- httparty (LoadError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from C:/tmp/zendesk-helpcenter-export-master/zendesk-helpcenter-export.rb:2:in `<main>'

**Comment by pjmuller** [comment]
Hi there,

it seems that you don't have the gems installed. Try to run

```
gem install httparty
```

The same will need to happen for the other gems if they are not present.

Does this solve your problem?

**Comment by ComprensivoDK** [comment]
Some of the gems listed from the script you link to can't be found... I
have installed most of them, but it still fails...

Now i get this error:

[image: 2016-01-14 12_40_56-Start Command Prompt with Ruby.png]

Carsten Falborg
Zendesk Expert
Comprensivo

Website http://www.comprensivo.dk  http://www.facebook.com/comprensivodk
  http://dk.linkedin.com/in/carstenfalborg
http://twitter.com/ComprensivoDK

tor. 14. jan. 2016 kl. 11.53 skrev Pieterjan Muller <
notifications@github.com>:

**Comment by pjmuller** [comment]
Hi Carsten,

please post your responses on https://github.com/pjmuller/zendesk-helpcenter-export/issues/2#issuecomment-171611061 and not through mail as the attached image does not show.

Can you upload the screenshot to for example imgur.com, and then post it here?

**Comment by pjmuller** [comment]
Hi Carsten,

is it solved now so that we can close this issue?
