### ISSUE TITLE
syntax error, unexpected ')', expecting keyword_end

### ISSUE THREAD

**Issue by ebuychance** [pjmuller/zendesk-helpcenter-export#3]
zendesk-helpcenter-export.rb:57: syntax error, unexpected tLABEL, expecting ')'
 def initialize(email_user:, password:, zedesk_subdomain...
                           ^
zendesk-helpcenter-export.rb:57: syntax error, unexpected ')', expecting keyword_end
zendesk-helpcenter-export.rb:221: syntax error, unexpected keyword_end, expecting $end

Any idea what this error is from? 

ENV
ruby 9.1.3p484 (2013-11-22 revision 43786) [i686-linux]

file-utils (0.1.1)
httparty (0.13.7)
json (1.8.3)
multi_xml (0.5.5)

**Comment by ebuychance** [comment]
I setup new env with ruby 2.3 and things are working now.

**Comment by pjmuller** [comment]
Hi Chance,

sorry I got back to you after a long while (health issues in the family).
Yes indeed, we are using keyword arguments.
For that you need at least ruby 2.0.

Happy that you figured it out yourself :)
