### ISSUE TITLE
117:in `article_html_content': undefined method `gsub' for nil:NilClass 

### ISSUE THREAD

**Issue by ebuychance** [pjmuller/zendesk-helpcenter-export#4]
zendesk-helpcenter-export.rb:117:in `article_html_content': undefined method`gsub' for nil:NilClass (NoMethodError)
    from zendesk-helpcenter-export.rb:83:in `block (4 levels) in to_html!'

Nil exception error. Looks like an article body is missing?

**Comment by pjmuller** [comment]
Hi Chance,

I just posted an update of the script that should not fail when the content is empty.
Can you try that?

**Comment by ebuychance** [comment]
That fixed the the reported error. 
But now it hits this:
zendesk-helpcenter-export.rb:83:in `initialize': No such file or directory @ rb_sysopen

Having slashes '/'  in the article names is the issue. Need to escape/replace them before trying to open the file structure.

So I added slugify to the 'name' on line 82. Seems like it is slugified in the directory functions so this change should not break any of the directory creating/renaming logic?

``` ruby
file_path = "#{article_dir}#{slugify(article['name'])}.html"
```

Thanks

**Comment by yoshprogrammer** [comment]
@ebuychance I'm not seeing where that would end up breaking directory creating/renaming logic, i'm trying it right now with a large HC. i'll report back if any issues

**Comment by pjmuller** [comment]
Hi @ebuychance , I followed your suggestions in pull request #7 which is merged into master.

If you pull the code you won't have the problem anymore (moreover I've made a lot of other different improvements today.

If there is anything else I can help with, please let me know. For now I'll mark this issue as closed
