### ISSUE TITLE
(Errno::EINVAL) Question mark in title

### ISSUE THREAD

**Issue by Kosai106** [pjmuller/zendesk-helpcenter-export#6]
Just a quickie, I've been tasked with downloading our entire Zendesk knowledgebase and thus I came across this neat script.

It works just as advertised, which I'm very happy about. However, I'm facing pretty big issue...
All of our article titles contains question marks, and seeing as Windows can't save files containing question marks in the name, I instead get an error. (As seen below.)

![issue](https://cloud.githubusercontent.com/assets/6379824/13601951/e654e48a-e533-11e5-8740-29626b874656.png)
Notice, I've renamed two articles to verify that it's the question marks that are causing the issues.

I thought I could be smart by editing the script with a little piece of regex to remove any special characters from the saved filename, however I've had no luck with this.

Any help would be much appreciated as I'd rather not rename 86 articles. (516 if you include the other locales we support...)

Cheers!

**Comment by pjmuller** [comment]
Hi Kosai,

I fixed it through the pull request  #7 slugify article names to avoid incorrect html file name

Now you can use whatever signs you want in the article name.

Can you let me know if this fixed it? Just repull master, delete all your export files, and run the script again
